
// NOTE: Tags in this file are pulled from MDN's SVG element reference.
// https://developer.mozilla.org/en-US/docs/Web/SVG/Element

// NOTE: The `<switch>` SVG element has been disabled because `switch` is a
// keyword in JavaScript. Use `h('switch')` until a solution is found.
// https://developer.mozilla.org/en-US/docs/Web/SVG/Element/switch

// NOTE: /* @__PURE__ */ annotations inform tools like ESBuild, Rollup, and
// Uglify that these function calls do not produce side effects and can safely
// be removed when unused.

import { h } from '../shim'

export const a = /* @__PURE__ */ h('a')
export const animate = /* @__PURE__ */ h('animate')
export const animateMotion = /* @__PURE__ */ h('animateMotion')
export const animateTransform = /* @__PURE__ */ h('animateTransform')
export const circle = /* @__PURE__ */ h('circle')
export const clipPath = /* @__PURE__ */ h('clipPath')
export const colorProfile = /* @__PURE__ */ h('color-profile') // <color-profile>
export const defs = /* @__PURE__ */ h('defs')
export const desc = /* @__PURE__ */ h('desc')
export const discard = /* @__PURE__ */ h('discard')
export const ellipse = /* @__PURE__ */ h('ellipse')
export const feBlend = /* @__PURE__ */ h('feBlend')
export const feColorMatrix = /* @__PURE__ */ h('feColorMatrix')
export const feComponentTransfer = /* @__PURE__ */ h('feComponentTransfer')
export const feComposite = /* @__PURE__ */ h('feComposite')
export const feConvolveMatrix = /* @__PURE__ */ h('feConvolveMatrix')
export const feDiffuseLighting = /* @__PURE__ */ h('feDiffuseLighting')
export const feDisplacementMap = /* @__PURE__ */ h('feDisplacementMap')
export const feDistantLight = /* @__PURE__ */ h('feDistantLight')
export const feDropShadow = /* @__PURE__ */ h('feDropShadow')
export const feFlood = /* @__PURE__ */ h('feFlood')
export const feFuncA = /* @__PURE__ */ h('feFuncA')
export const feFuncB = /* @__PURE__ */ h('feFuncB')
export const feFuncG = /* @__PURE__ */ h('feFuncG')
export const feFuncR = /* @__PURE__ */ h('feFuncR')
export const feGaussianBlur = /* @__PURE__ */ h('feGaussianBlur')
export const feImage = /* @__PURE__ */ h('feImage')
export const feMerge = /* @__PURE__ */ h('feMerge')
export const feMergeNode = /* @__PURE__ */ h('feMergeNode')
export const feMorphology = /* @__PURE__ */ h('feMorphology')
export const feOffset = /* @__PURE__ */ h('feOffset')
export const fePointLight = /* @__PURE__ */ h('fePointLight')
export const feSpecularLighting = /* @__PURE__ */ h('feSpecularLighting')
export const feSpotLight = /* @__PURE__ */ h('feSpotLight')
export const feTile = /* @__PURE__ */ h('feTile')
export const feTurbulence = /* @__PURE__ */ h('feTurbulence')
export const filter = /* @__PURE__ */ h('filter')
export const foreignObject = /* @__PURE__ */ h('foreignObject')
export const g = /* @__PURE__ */ h('g')
export const hatch = /* @__PURE__ */ h('hatch')
export const hatchpath = /* @__PURE__ */ h('hatchpath')
export const image = /* @__PURE__ */ h('image')
export const line = /* @__PURE__ */ h('line')
export const linearGradient = /* @__PURE__ */ h('linearGradient')
export const marker = /* @__PURE__ */ h('marker')
export const mask = /* @__PURE__ */ h('mask')
export const mesh = /* @__PURE__ */ h('mesh')
export const meshgradient = /* @__PURE__ */ h('meshgradient')
export const meshpatch = /* @__PURE__ */ h('meshpatch')
export const meshrow = /* @__PURE__ */ h('meshrow')
export const metadata = /* @__PURE__ */ h('metadata')
export const mpath = /* @__PURE__ */ h('mpath')
export const path = /* @__PURE__ */ h('path')
export const pattern = /* @__PURE__ */ h('pattern')
export const polygon = /* @__PURE__ */ h('polygon')
export const polyline = /* @__PURE__ */ h('polyline')
export const radialGradient = /* @__PURE__ */ h('radialGradient')
export const rect = /* @__PURE__ */ h('rect')
export const script = /* @__PURE__ */ h('script')
export const set = /* @__PURE__ */ h('set')
export const solidcolor = /* @__PURE__ */ h('solidcolor')
export const stop = /* @__PURE__ */ h('stop')
export const style = /* @__PURE__ */ h('style')
export const svg = /* @__PURE__ */ h('svg')
// export const switch = /* @__PURE__ */ h('switch')
export const symbol = /* @__PURE__ */ h('symbol')
export const text = /* @__PURE__ */ h('text')
export const textPath = /* @__PURE__ */ h('textPath')
export const title = /* @__PURE__ */ h('title')
export const tspan = /* @__PURE__ */ h('tspan')
export const unknown = /* @__PURE__ */ h('unknown')
export const use = /* @__PURE__ */ h('use')
export const view = /* @__PURE__ */ h('view')
